#!/bin/bash
python -m black *.py --line-length=120 --preview
python -m black **/*.py --line-length=120 --preview
python -m black ikflow/**/*.py --line-length=120 --preview

# Clear pynbs
jupyter nbconvert --clear-output --inplace notebooks/*.ipynb
