#!/bin/bash
uv run python -m black **/*.py --line-length=120 --preview
uv run python -m black ikflow/**/*.py --line-length=120 --preview

# Clear pynbs
jupyter nbconvert --clear-output --inplace notebooks/*.ipynb
